---
title: "Concentration"
author: "Diego Arias"
date: "12/2/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(scales)
library(tidyverse)
library(googlesheets4)
library(janitor)
library(stats)
library(fs)
library(readxl)
library(infer)
library(pracma)
library(reshape2)
library(moderndive)
library(gt)
library(ggplot2)
```

```{r}
m <- read_csv("m.csv") %>%
  drop_na()
```


```{r, visualizing data points for concentration}
data_plot_concentration<- ggplot(m, aes(x = concentration_r,fill=concentration_r)) +
  geom_bar(aes(y = (..count..)/sum(..count..))) +
  labs(title="Distribution of Data Points", x="Different Values", y= "Percentage") +
  scale_y_continuous(labels = scales::percent)+
  theme(axis.text.x = element_blank())

data_plot_concentration


write_rds(data_plot_concentration, "~/Desktop/R studio/final_project_data_cleanup/shiny/concentration/barplot_concentration.rds")

```


```{r, visualizing findings for concentration}
concentration_violin <- m %>%
  filter(concentration_r %in% c("Humanities","Social Sciences","STEM"))%>%
  ggplot(aes(x=concentration_r, y = n_same_concentration, color = concentration_r)) +
  geom_violin() +
  stat_summary(fun.y = mean, geom = "point") +
  geom_jitter(shape = 16, color = "black", size = .5) + 
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title = "Distribution of Same Concentration Friends per Respondent Concentration", y = "Number of Same Concentration Friends") +
  theme(legend.position = "none")

concentration_violin

write_rds(concentration_violin, "~/Desktop/R studio/final_project_data_cleanup/shiny/concentration/violin_concentration.rds")
```


```{r, creating random sample for concentration}
m_random_concentration<-
    
    tibble(replicate = 1:10000)%>%
  
    mutate(concentration_r = sample(c("Humanities","Social Sciences","STEM"), size=10000, replace = TRUE, prob=c(0.12,0.36,0.53)))%>%
  
  mutate(concentration_p1 = sample(c("Humanities","Social Sciences","STEM"), size=10000, replace = TRUE, prob=c(0.12,0.36,0.53)))%>%
  
  mutate(concentration_p2 = sample(c("Humanities","Social Sciences","STEM"), size=10000, replace = TRUE, prob=c(0.12,0.36,0.53)))%>%
  
  mutate(concentration_p3 = sample(c("Humanities","Social Sciences","STEM"), size=10000, replace = TRUE, prob=c(0.12,0.36,0.53)))%>%
  
  mutate(concentration_p4 = sample(c("Humanities","Social Sciences","STEM"), size=10000, replace = TRUE, prob=c(0.12,0.36,0.53)))%>%
  
  mutate(n_same_concentration= NA)

# We repeat the same for loop as we did in the beginning with our collected data, but with the sample we generated with the for loop above:

for (i in 1:10000) {

respondent_concentration<-m_random_concentration$concentration_r[i]

count=0

if(respondent_concentration==m_random_concentration$concentration_p1[i])
{count<-count+1}else{
count<-count}

if(respondent_concentration==m_random_concentration$concentration_p2[i])
{count<-count+1}else{
count<-count}

if(respondent_concentration==m_random_concentration$concentration_p3[i])
{count<-count+1}else{
count<-count}

if(respondent_concentration==m_random_concentration$concentration_p4[i])
{count<-count+1}else{
count<-count}

m_random_concentration$n_same_concentration[i]<-count}
```


```{r, STEM permutation test}
stem_replications <- m_random_concentration %>%
   filter(concentration_r=="STEM")%>%
  select(n_same_concentration)%>%
  rep_sample_n(size = 55, replace = TRUE, reps = 10000) %>% 
  group_by(replicate) %>% 
  summarize(mean_same_concentration = mean(n_same_concentration))

mean_observed_stem <- as.numeric(m%>%
  filter(concentration_r=="STEM")%>%
  summarize(mean=mean(n_same_concentration)))

stem_permutation_plot<- stem_replications %>%
  ggplot(aes(x=mean_same_concentration))+
  geom_density(fill = "seagreen1")+
  geom_vline(xintercept=mean_observed_stem, color = "blue") + 
  labs(title = "Distribution of Mean Number of Friends Studying STEM per Respondent Studying STEM Under the Null Hypothesis", subtitle = "Our observed value, shown in blue, is smaller than we would expect under random friend assignment", x = "Mean Number of `Same Academic Status` Friends (STEM) per Replication", y = "Density")+
  theme(legend.position = "none")

stem_permutation_plot

write_rds(stem_permutation_plot, "~/Desktop/R studio/final_project_data_cleanup/shiny/concentration/stem_permutation.rds")
```


```{r, Humanities permutation test}
humanities_replications <- m_random_concentration %>%
   filter(concentration_r=="Humanities")%>%
  select(n_same_concentration)%>%
  rep_sample_n(size = 14, replace = TRUE, reps = 10000) %>% 
  group_by(replicate) %>% 
  summarize(mean_same_concentration = mean(n_same_concentration))

mean_observed_humanities <- as.numeric(m%>%
  filter(concentration_r=="Humanities")%>%
  summarize(mean=mean(n_same_concentration)))

humanities_permutation_plot<- humanities_replications %>%
  ggplot(aes(x=mean_same_concentration))+
  geom_density(fill = "seagreen1")+
  geom_vline(xintercept=mean_observed_stem, color = "blue") + 
 labs(title = "Distribution of Mean Number of Friends Studying Humanities per Respondent Studying Humanities Under the Null Hypothesis", subtitle = "Our observed value, shown in blue, is smaller than we would expect under random friend assignment", x = "Mean Number of `Same Academic Status` Friends (Humanities) per Replication", y = "Density")

humanities_permutation_plot

write_rds(humanities_permutation_plot, "~/Desktop/R studio/final_project_data_cleanup/shiny/concentration/humanities_permutation.rds")
```


```{r, Social Sciences permutation test}
social_sciences_replications <- m_random_concentration %>%
   filter(concentration_r=="Social Sciences")%>%
  select(n_same_concentration)%>%
  rep_sample_n(size = 31, replace = TRUE, reps = 10000) %>% 
  group_by(replicate) %>% 
  summarize(mean_same_concentration = mean(n_same_concentration))

mean_observed_social_sciences <- as.numeric(m%>%
  filter(concentration_r=="Social Sciences")%>%
  summarize(mean=mean(n_same_concentration)))

social_sciences_permutation_plot<- social_sciences_replications %>%
  ggplot(aes(x=mean_same_concentration))+
  geom_density(fill = "seagreen1")+
  geom_vline(xintercept=mean_observed_stem, color = "blue") + 
labs(title = "Distribution of Mean Number of Friends Studying Social Science per Respondent Studying Social Science Under the Null Hypothesis", subtitle = "Our observed value, shown in blue, is smaller than we would expect under random friend assignment", x = "Mean Number of `Same Academic Status` Friends (Social Science) per Replication", y = "Density")+
  theme(legend.position = "none")

social_sciences_permutation_plot

write_rds(social_sciences_permutation_plot, "~/Desktop/R studio/final_project_data_cleanup/shiny/concentration/social_sciences_permutation.rds")
```
