---
title: "First-Gen"
author: "Diego Arias"
date: "11/29/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(tidyverse)
library(googlesheets4)
library(janitor)
library(stats)
library(fs)
library(readxl)
library(infer)
library(pracma)
library(reshape2)
library(moderndive)
library(gt)
library(ggplot2)
```

```{r}
m <- read_csv("m.csv")%>%
  drop_na()

```


```{r first gen distribution}

data_plot_firstgen<- ggplot(m, aes(x = firstgen_r, fill = firstgen_r))+
  geom_bar(aes(y = (..count..)/sum(..count..))) +
  labs(title="Distribution of Data Points", x="Different Values", y= "Percentage")  +
  scale_y_continuous(labels = scales::percent)+
  theme(legend.position = "none")+
  theme(
  plot.background = element_rect(fill = "white"),
  panel.background = element_rect(fill = "white"),
  axis.line.x = element_line(color = "grey"))+
  theme(legend.title = element_blank())

data_plot_firstgen

write_rds(data_plot_firstgen, "~/Documents/final_project_data_cleanup/shiny/firstgen/barplot_firstgen.rds")
```


```{r distribution of first-gen answers}
firstgen_violin <- m %>%
  ggplot(aes(x=firstgen_r, y = n_same_firstgen, color = firstgen_r)) +
  geom_violin() +
  stat_summary(fun.y = mean, geom = "point") +
  geom_jitter(shape = 16, color = "black", size = .5, height = 0.1, width = 0.2) + 
  labs(title = "Distribution of Same Race Friends per Respondent First-Gen", y = "Number of Same First-Gen Friends", x = "Respondent: First-Gen?") +
  theme(legend.position = "none")+
  theme(
  plot.background = element_rect(fill = "white"),
  panel.background = element_rect(fill = "white"),
  axis.line.x = element_line(color = "grey"))+
  theme(legend.title = element_blank())

firstgen_violin

write_rds(firstgen_violin, "~/Documents/final_project_data_cleanup/shiny/firstgen/violin_firstgen.rds")
```


```{r}
m_random_firstgen<-
    
    tibble(replicate = 1:10000)%>%
  
    mutate(firstgen_r = sample(c("Yes","No"), size=10000, replace = TRUE, prob=c(0.12,0.88)))%>%
  
  mutate(firstgen_p1 = sample(c("Yes","No"), size=10000, replace = TRUE, prob=c(0.12,0.88)))%>%
  
  mutate(firstgen_p2 = sample(c("Yes","No"), size=10000, replace = TRUE, prob=c(0.12,0.88)))%>%
  
  mutate(firstgen_p3 = sample(c("Yes","No"), size=10000, replace = TRUE, prob=c(0.12,0.88)))%>%
  
  mutate(firstgen_p4 = sample(c("Yes","No"), size=10000, replace = TRUE, prob=c(0.12,0.88)))%>%
  
  mutate(n_same_firstgen = NA)

# We repeat the same for loop as we did in the beginning with our collected data, but with the sample we generated with the for loop above:

for (i in 1:10000) {

respondent_firstgen<-m_random_firstgen$firstgen_r[i]

count=0

if(respondent_firstgen==m_random_firstgen$firstgen_p1[i])
{count<-count+1}else{
count<-count}

if(respondent_firstgen==m_random_firstgen$firstgen_p2[i])
{count<-count+1}else{
count<-count}

if(respondent_firstgen==m_random_firstgen$firstgen_p3[i])
{count<-count+1}else{
count<-count}

if(respondent_firstgen==m_random_firstgen$firstgen_p4[i])
{count<-count+1}else{
count<-count}

m_random_firstgen$n_same_firstgen[i]<-count}
```


```{r first gen permuation 1}

firstgen_yes_replications <- m_random_firstgen %>%
   filter(firstgen_r=="Yes")%>%
  select(n_same_firstgen)%>%
  rep_sample_n(size = 31, replace = TRUE, reps = 10000) %>% 
  group_by(replicate) %>% 
  summarize(mean_same_firstgen = mean(n_same_firstgen))

mean_observed_firstgen_yes <- as.numeric(m%>%
  filter(firstgen_r=="Yes")%>%
  summarize(mean=mean(n_same_firstgen)))

firstgen_yes_permutation_plot<- firstgen_yes_replications %>%
  ggplot(aes(x=mean_same_firstgen))+
  geom_density(fill = "seagreen1")+
  geom_vline(xintercept=mean_observed_firstgen_yes, color = "blue") + 
 labs(title = "Distribution of Mean Number of First-Gen Friends per First-Gen Respondent Under the Null Hypothesis", subtitle = "Our observed value, shown in blue, is smaller than we would expect under random friend assignment", x = "Mean Number of `Same Status` Friends (First-Gen per Replication",y = "Density")+
  theme(legend.position = "none")+
  theme(
  plot.background = element_rect(fill = "white"),
  panel.background = element_rect(fill = "white"),
  axis.line.x = element_line(color = "grey"))+
  theme(legend.title = element_blank())

firstgen_yes_permutation_plot

write_rds(firstgen_yes_permutation_plot, "~/Documents/final_project_data_cleanup/shiny/firstgen/firstgen_yes_permutation.rds")
```


```{r first gen perm 2}
firstgen_no_replications <- m_random_firstgen %>%
   filter(firstgen_r=="No")%>%
  select(n_same_firstgen)%>%
  rep_sample_n(size = 73, replace = TRUE, reps = 10000) %>% 
  group_by(replicate) %>% 
  summarize(mean_same_firstgen = mean(n_same_firstgen))

mean_observed_firstgen_no <- as.numeric(m%>%
  filter(firstgen_r=="No")%>%
  summarize(mean=mean(n_same_firstgen)))

firstgen_no_permutation_plot<- firstgen_no_replications %>%
  ggplot(aes(x=mean_same_firstgen))+
  geom_density(fill = "seagreen1")+
  geom_vline(xintercept=mean_observed_firstgen_no, color = "blue") + 
 labs(title = "Distribution of Mean Number of Non-First-Gen Friends per Non-First-Gen Respondent Under the Null Hypothesis", subtitle = "Our observed value, shown in blue, is smaller than we would expect under random friend assignment", x = "Mean Number of `Same Status` Friends (Non-First-Genl) per Replication",y = "Density")+
  theme(legend.position = "none")+
  theme(
  plot.background = element_rect(fill = "white"),
  panel.background = element_rect(fill = "white"),
  axis.line.x = element_line(color = "grey"))+
  theme(legend.title = element_blank())

firstgen_no_permutation_plot

write_rds(firstgen_no_permutation_plot, "~/Documents/final_project_data_cleanup/shiny/firstgen/firstgen_no_permutation.rds")
```
