---
title: "International"
author: "Diego Arias"
date: "12/2/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(tidyverse)
library(googlesheets4)
library(janitor)
library(stats)
library(fs)
library(readxl)
library(infer)
library(pracma)
library(reshape2)
library(moderndive)
library(gt)
library(ggplot2)
```

```{r}
m <- read_csv("m.csv")%>%
  drop_na()
```


```{r}
data_plot_international<- ggplot(m, aes(x = international_r, fill = international_r)) +
  geom_bar(aes(y = (..count..)/sum(..count..))) +
  labs(title="Distribution of Data Points", x="Different Values", y= "Percentage")  +
  scale_y_continuous(labels = scales::percent)+
  theme(legend.position = "none")

data_plot_international

write_rds(data_plot_international, "~/Desktop/R studio/final_project_data_cleanup/shiny/international/barplot_international.rds")
```


```{r}
international_violin <- m %>%
  ggplot(aes(x=international_r, y = n_same_international, color = international_r)) +
  geom_violin() +
  stat_summary(fun.y = mean, geom = "point") +
  geom_jitter(shape = 16, color = "black", size = .5) + 
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title = "Distribution of International Friends per Respondent", y = "Number of Same International Friends", x = "Respondent: International?") +
  theme(legend.position = "none")

international_violin

write_rds(international_violin, "~/Desktop/R studio/final_project_data_cleanup/shiny/international/violin_international.rds")
```


```{r}
m_random_international<-
    
    tibble(replicate = 1:10000)%>%
  
    mutate(international_r = sample(c("Yes","No"), size=10000, replace = TRUE, prob=c(0.12,0.88)))%>%
  
  mutate(international_p1 = sample(c("Yes","No"), size=10000, replace = TRUE, prob=c(0.12,0.88)))%>%
  
  mutate(international_p2 = sample(c("Yes","No"), size=10000, replace = TRUE, prob=c(0.12,0.88)))%>%
  
  mutate(international_p3 = sample(c("Yes","No"), size=10000, replace = TRUE, prob=c(0.12,0.88)))%>%
  
  mutate(international_p4 = sample(c("Yes","No"), size=10000, replace = TRUE, prob=c(0.12,0.88)))%>%
  
  mutate(n_same_international = NA)

# We repeat the same for loop as we did in the beginning with our collected data, but with the sample we generated with the for loop above:

for (i in 1:10000) {

respondent_international<-m_random_international$international_r[i]

count=0

if(respondent_international==m_random_international$international_p1[i])
{count<-count+1}else{
count<-count}

if(respondent_international==m_random_international$international_p2[i])
{count<-count+1}else{
count<-count}

if(respondent_international==m_random_international$international_p3[i])
{count<-count+1}else{
count<-count}

if(respondent_international==m_random_international$international_p4[i])
{count<-count+1}else{
count<-count}

m_random_international$n_same_international[i]<-count}
```


```{r}

international_yes_replications <- m_random_international %>%
   filter(international_r=="Yes")%>%
  select(n_same_international)%>%
  rep_sample_n(size = 12, replace = TRUE, reps = 10000) %>% 
  group_by(replicate) %>% 
  summarize(mean_same_international = mean(n_same_international))

mean_observed_international_yes <- as.numeric(m%>%
  filter(international_r=="Yes")%>%
  summarize(mean=mean(n_same_international)))

international_yes_permutation_plot<- international_yes_replications %>%
  ggplot(aes(x=mean_same_international))+
  geom_density(fill = "seagreen1")+
  geom_vline(xintercept=mean_observed_international_yes, color = "blue") + 
   labs(title = "Distribution of Mean Number of International Friends per International Respondent Under the Null Hypothesis", subtitle = "Our observed value, shown in blue, is smaller than we would expect under random friend assignment", x = "Mean Number of `Same Status` Friends (International) per Replication",y = "Density")+
  theme(legend.position = "none")

international_yes_permutation_plot

write_rds(international_yes_permutation_plot, "~/Desktop/R studio/final_project_data_cleanup/shiny/international/international_yes_permutation.rds")
```


```{r}
international_no_replications <- m_random_international %>%
   filter(international_r=="No")%>%
  select(n_same_international)%>%
  rep_sample_n(size = 92, replace = TRUE, reps = 10000) %>% 
  group_by(replicate) %>% 
  summarize(mean_same_international = mean(n_same_international))

mean_observed_international_no <- as.numeric(m%>%
  filter(international_r=="No")%>%
  summarize(mean=mean(n_same_international)))

international_no_permutation_plot<- international_no_replications %>%
  ggplot(aes(x=mean_same_international))+
  geom_density(fill="seagreen1")+
  geom_vline(xintercept=mean_observed_international_no, color = "blue") + 
   labs(title = "Distribution of Mean Number of Non-International Friends per Non-International Respondent Under the Null Hypothesis", subtitle = "Our observed value, shown in blue, is smaller than we would expect under random friend assignment", x = "Mean Number of `Same Status` Friends (Non-International) per Replication",y = "Density")+
  theme(legend.position = "none")

international_no_permutation_plot

write_rds(international_no_permutation_plot, "~/Desktop/R studio/final_project_data_cleanup/shiny/international/international_no_permutation.rds")
```