---
title: "Race"
author: "Diego Arias"
date: "11/29/2019"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

library(tidyverse)
library(googlesheets4)
library(janitor)
library(stats)
library(fs)
library(readxl)
library(infer)
library(pracma)
```

```{r}
m <- read_csv("m.csv") %>%
  drop_na()
```

```{r, visualizing data points for race}
data_plot_race<- ggplot(m, aes(x = race_r,fill=race_r)) +
  geom_bar(aes(y = (..count..)/sum(..count..))) +
  labs(title="Distribution of Data Points", x="Respondent Race", y= "Percentage") +
  scale_y_continuous(labels = scales::percent) +
theme(axis.text.x = element_blank())

data_plot_race


write_rds(data_plot_race, "~/Desktop/R studio/final_project_data_cleanup/shiny/race/barplot_race.rds")


```


```{r, visualizing findings for race}
race_violin <- m %>%
  filter(race_r %in% c("White","Black or African American","Asian","Hispanic or Latino","Two or more races")) %>%
  ggplot(aes(x=race_r, y = n_same_race, color = race_r)) +
  geom_violin() +
  stat_summary(fun.y = mean, geom = "point") +
  geom_jitter(shape = 16, color = "black", size = .5) + 
  labs(title = "Distribution of Same Race Friends per Respondent race", x="Respondent Race", y = "Number of Same Race Friends")+
  theme(axis.text.x = element_blank())

race_violin


write_rds(race_violin, "~/Desktop/R studio/final_project_data_cleanup/shiny/race/violin_race.rds")
```


```{r, race permutation test}
# We ran a permutation below to compare to the data collected above. This permutation is based on the overall race makeup of Harvard-- NOT the race makeup of just friend groups. We will create a random sample with the proportions reported by Harvard and compare the outcome to the racial makeup of friend groups to see if there is self-segregation:

m_random_race<-
    
    tibble(replicate = 1:10000)%>%
  
    mutate(race_r = sample(c("White","Black or African American","Asian","Hispanic or Latino","Two or more races"), size=10000, replace = TRUE, prob=c(0.513, 0.1116, 0.228, .093, 0.00)))%>%
  
  mutate(race_p1 = sample(c("White","Black or African American","Asian","Hispanic or Latino","Two or more races"), size=10000, replace = TRUE, prob=c(0.513, 0.1116, 0.228, .093, 0.00)))%>%
  
  mutate(race_p2 = sample(c("White","Black or African American","Asian","Hispanic or Latino","Two or more races"), size=10000, replace = TRUE, prob=c(0.513, 0.1116, 0.228, .093, 0.00)))%>%
  
  mutate(race_p3 = sample(c("White","Black or African American","Asian","Hispanic or Latino","Two or more races"), size=10000, replace = TRUE, prob=c(0.513, 0.1116, 0.228, .093, 0.00)))%>%
  
  mutate(race_p4 = sample(c("White","Black or African American","Asian","Hispanic or Latino","Two or more races"), size=10000, replace = TRUE, prob=c(0.513, 0.1116, 0.228, .093, 0.00)))%>%
  
  mutate(n_same_race= NA)

# We repeat the same for loop as we did in the beginning with our collected data, but with the sample we generated with the for loop above:

for (i in 1:10000) {

respondent_race<-m_random_race$race_r[i]

count=0

if(respondent_race==m_random_race$race_p1[i])
{count<-count+1}else{
count<-count}

if(respondent_race==m_random_race$race_p2[i])
{count<-count+1}else{
count<-count}

if(respondent_race==m_random_race$race_p3[i])
{count<-count+1}else{
count<-count}

if(respondent_race==m_random_race$race_p4[i])
{count<-count+1}else{
count<-count}

m_random_race$n_same_race[i]<-count}
```

```{r}

# We use the randomized sample from above and look at the white distribution and do various graphical representations of it:
white_replications <- m_random_race %>%
   filter(race_r=="White")%>%
  select(n_same_race)%>%
  rep_sample_n(size = 44, replace = TRUE, reps = 10000) %>% 
  group_by(replicate) %>% 
  summarize(mean_same_race = mean(n_same_race))

# Above we took the mean of the same race distribution for white respondents and their friends. Below we make this a numberical mean:

mean_observed_white <- as.numeric(m%>%
  filter(race_r=="White")%>%
  summarize(mean=mean(n_same_race)))

# Using the mean distribution of white race matches for white respondents, we create a density plot with the permutation data: 

white_permutation_plot<- white_replications %>%
  ggplot(aes(x=mean_same_race))+
  geom_density(fill = "seagreen1")+
  geom_vline(xintercept=mean_observed_white, color = "blue") + 
 labs(title = "Distribution of Mean Number of White Friends per White Respondent Under the Null Hypothesis", subtitle = "Our observed value, shown in blue, is smaller than we would expect under random friend assignment", x = "Mean Number of Same Race Friends (White) per Replication",y = "Density")
white_permutation_plot


write_rds(white_permutation_plot, "~/Desktop/R studio/final_project_data_cleanup/shiny/race/white_permutation.rds")
```

```{r Asian permutation}
# We use the permutation data here for Asian distribution and corresponding graphical representations. We repeat the same process as above:

asian_replications <- m_random_race%>%
  filter(race_r=="Asian")%>%
  select(n_same_race)%>%
  rep_sample_n(size = 28, replace = TRUE, reps = 10000) %>% 
  group_by(replicate) %>% 
  summarize(mean_same_race = mean(n_same_race))

mean_observed_asian <- as.numeric(m%>%
  filter(race_r=="Asian")%>%
  summarize(mean=mean(n_same_race)))

asian_permutation_plot<-asian_replications %>%
  ggplot(aes(x=mean_same_race))+
  geom_density(fill = "seagreen1")+
  geom_vline(xintercept=mean_observed_asian, color = "blue") + 
  labs(title = "Distribution of Mean Number of Asian Friends per Asian Respondent Under the Null Hypothesis", subtitle = "Our observed value, shown in blue, is smaller than we would expect under random friend assignment", x = "Mean Number of Same Race Friends (Asian) per Replication",y = "Density")

asian_permutation_plot



#write_rds(asian_permutation_plot, "~/Desktop/R studio/final_project_data_cleanup/shiny/race/asian_permutation.rds")

```

```{r Black permutation}
# We repeat the process with the Black permutation data. We use the same process as we used for the white distribution: 

black_replications <- m_random_race%>%
  filter(race_r=="Black or African American")%>%
  select(n_same_race)%>%
  rep_sample_n(size = 12, replace = TRUE, reps = 10000) %>% 
  group_by(replicate) %>% 
  summarize(mean_same_race = mean(n_same_race))

mean_observed_black <- as.numeric(m%>%
  filter(race_r=="Black or African American")%>%
  summarize(mean=mean(n_same_race)))

black_permutation_plot <- black_replications %>%
  ggplot(aes(x=mean_same_race))+
  geom_density(fill = "seagreen1")+
  geom_vline(xintercept=mean_observed_black, color = "blue") + 
labs(title = "Distribution of Mean Number of Black/African American Friends per Black/African American Respondent Under the Null Hypothesis", subtitle = "Our observed value, shown in blue, is smaller than we would expect under random friend assignment", x = "Mean Number of Same Race Friends (Black/African American) per Replication",y = "Density")


black_permutation_plot

write_rds(black_permutation_plot, "~/Desktop/R studio/final_project_data_cleanup/shiny/race/black_permutation.rds")

```

```{r Hispanic permuatation data}
# We do the same for the Hispanic permutation data. We use the same process as we did with the white permutation data:

hispanic_replications <-m_random_race%>%
  filter(race_r=="Hispanic or Latino")%>%
  select(n_same_race)%>%
  rep_sample_n(size = 10, replace = TRUE, reps = 10000) %>% 
  group_by(replicate) %>% 
  summarize(mean_same_race = mean(n_same_race))

mean_observed_hispanic <- as.numeric(m%>%
  filter(race_r=="Hispanic or Latino")%>%
  summarize(mean=mean(n_same_race)))

hispanic_permutation_plot <- hispanic_replications %>%
  ggplot(aes(x=mean_same_race))+
  geom_density(fill = "seagreen1")+
  geom_vline(xintercept=mean_observed_hispanic, color = "blue") + 
labs(title = "Distribution of Mean Number of Hispanic/Latino Friends per Hispanic/Latino Respondent Under the Null Hypothesis", subtitle = "Our observed value, shown in blue, is smaller than we would expect under random friend assignment", x = "Mean Number of Same Race (Hispanic/Latino) Friends per Replication",y = "Density")



hispanic_permutation_plot 

write_rds(hispanic_permutation_plot, "~/Desktop/R studio/final_project_data_cleanup/shiny/race/hispanic_permutation.rds")

```