---
title: "Religion"
author: "Diego Arias"
date: "11/29/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(tidyverse)
library(googlesheets4)
library(janitor)
library(stats)
library(fs)
library(readxl)
library(infer)
library(pracma)
```

```{r}
m <- read_csv("m.csv")%>%
  drop_na()
```


```{r religion distribution}
data_plot_religion<- ggplot(m, aes(x = religion_r,fill=religion_r)) +
  geom_bar(aes(y = (..count..)/sum(..count..))) +
  labs(title="Distribution of Data Points", x="Different Values", y= "Percentage") +
  scale_y_continuous(labels = scales::percent) +
  theme(legend.position = "none")+
  theme(
  plot.background = element_rect(fill = "white"),
  panel.background = element_rect(fill = "white"),
  axis.line.x = element_line(color = "grey"))+
  theme(legend.title = element_blank())

data_plot_religion

write_rds(data_plot_religion, "~/Documents/final_project_data_cleanup/shiny/religion/barplot_religion.rds")

```

```{r}

# NOT SURE ABOUT CODING HERE-- I replaced n_same_concentreation with n_same_religion and religion_r so I might be wrong
religion_violin <- m %>%
  filter(religion_r %in% c("Christian","Agnostic or Atheist","Jewish"))%>%
  ggplot(aes(x=religion_r, y = n_same_religion, color = religion_r)) +
  geom_violin() +
  stat_summary(fun.y = mean, geom = "point") +
  geom_jitter(shape = 16, color = "black", size = .5, height= 0.1, width = 0.2) + 
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title = "Distribution of Same Religion Friends per Respondent Religion", y = "Number of Same Religion Friends", x = "Religion")+
    theme(axis.text.x = element_blank())+
 theme(
  plot.background = element_rect(fill = "white"),
  panel.background = element_rect(fill = "white"),
  axis.line.x = element_line(color = "grey"))+
  theme(legend.title = element_blank())+
   theme(axis.text.x = element_blank())

religion_violin

write_rds(religion_violin, "~/Documents/final_project_data_cleanup/shiny/religion/violin_religion.rds")
```



```{r, religion permutation test}
# We ran a permutation below to compare to the data collected above. This permutation is based on the overall religion makeup of Harvard-- NOT the religion makeup of just friend groups. We will create a random sample with the proportions reported by Harvard and compare the outcome to the racial makeup of friend groups to see if there is self-segregation:

m_random_religion<-
    
    tibble(replicate = 1:10000)%>%
  
    mutate(religion_r = sample(c("Christian","Jewish","	Muslim","Agnostic or Atheist", "Hindu", "Other"), size=10000, replace = TRUE, prob=c(0.352, 0.065, 0.031, .389, 0.028, .13))) %>%
  
  mutate(religion_p1 = sample(c("Christian","Jewish","	Muslim","Agnostic or Atheist", "Hindu", "Other"), size=10000, replace = TRUE, prob=c(0.352, 0.065, 0.031, .389, 0.028, .13))) %>%
  
  mutate(religion_p2 = sample(c("Christian","Jewish","	Muslim","Agnostic or Atheist", "Hindu", "Other"), size=10000, replace = TRUE, prob=c(0.352, 0.065, 0.031, .389, 0.028, .13))) %>%
  
  mutate(religion_p3 = sample(c("Christian","Jewish","	Muslim","Agnostic or Atheist", "Hindu", "Other"), size=10000, replace = TRUE, prob=c(0.352, 0.065, 0.031, .389, 0.028, .13))) %>%
  
  mutate(religion_p4 = sample(c("Christian","Jewish","	Muslim","Agnostic or Atheist", "Hindu", "Other"), size=10000, replace = TRUE, prob=c(0.352, 0.065, 0.031, .389, 0.028, .13))) %>%
  
  mutate(n_same_religion= NA)

# We repeat the same for loop as we did in the beginning with our collected data, but with the sample we generated with the for loop above:

for (i in 1:10000) {

respondent_religion<-m_random_religion$religion_r[i]

count=0

if(respondent_religion==m_random_religion$religion_p1[i])
{count<-count+1}else{
count<-count}

if(respondent_religion==m_random_religion$religion_p2[i])
{count<-count+1}else{
count<-count}

if(respondent_religion==m_random_religion$religion_p3[i])
{count<-count+1}else{
count<-count}

if(respondent_religion==m_random_religion$religion_p4[i])
{count<-count+1}else{
count<-count}

m_random_religion$n_same_religion[i]<-count}
```


```{r permutations for religion}
christian_replications <- m_random_religion%>%
  filter(religion_r=="Christian")%>%
  select(n_same_religion)%>%
  rep_sample_n(size = 58, replace = TRUE, reps = 10000) %>% 
  group_by(replicate) %>% 
  summarize(mean_same_religion = mean(n_same_religion))

mean_observed_christian <- as.numeric(m%>%
  filter(religion_r=="Christian")%>%
  summarize(mean=mean(n_same_religion)))

christian_permutation_plot<-christian_replications %>%
  ggplot(aes(x=mean_same_religion))+
  geom_density(fill = "seagreen1")+
  geom_vline(xintercept=mean_observed_christian, color = "blue") + 
  labs(title = "Distribution of Mean Number of Friends with Christian Beliefs per Respondent with Christian Belief Under the Null Hypothesis", subtitle = "Our observed value, shown in blue, is larger than we would expect under random friend assignment", x = "Number of Friends with Same Christian Beliefs per Respondent with Christian Beliefs per Replication", y = "Density")+
  theme(
  plot.background = element_rect(fill = "white"),
  panel.background = element_rect(fill = "white"),
  axis.line.x = element_line(color = "grey"))+
  theme(legend.title = element_blank())+
   theme(axis.text.x = element_blank())

 christian_permutation_plot

write_rds(christian_permutation_plot, "~/Documents/final_project_data_cleanup/shiny/religion/christian_permutation.rds")
             

```

```{r}
agnostic_or_atheist_replications <- m_random_religion %>%
  filter(religion_r=="Agnostic or Atheist")%>%
  select(n_same_religion)%>%
  rep_sample_n(size = 33, replace = TRUE, reps = 10000) %>% 
  group_by(replicate) %>% 
  summarize(mean_same_religion = mean(n_same_religion))

mean_observed_agnostic_or_atheist <- as.numeric(m%>%
  filter(religion_r=="Agnostic or Atheist")%>%
  summarize(mean=mean(n_same_religion)))

agnostic_or_atheist_permutation_plot<-agnostic_or_atheist_replications %>%
  ggplot(aes(x=mean_same_religion))+
  geom_density(fill = "seagreen1")+
  geom_vline(xintercept=mean_observed_agnostic_or_atheist, color = "blue") + 
  labs(title = "Distribution of Mean Friends' Same Religion Values (when respondent is Atheist/Agnostic) Under the Null Hypothesis", subtitle = "Our observed value, shown in blue, is smaller than we would expect under random friend assignment", x = "Number of Friends with Same Agnostic/Atheist Beliefs per Respondent with Agnostic/Atheist Beliefs per Replication", y = "Density")+
theme(
  plot.background = element_rect(fill = "white"),
  panel.background = element_rect(fill = "white"),
  axis.line.x = element_line(color = "grey"))+
  theme(legend.title = element_blank())+
   theme(axis.text.x = element_blank())

agnostic_or_atheist_permutation_plot


write_rds(agnostic_or_atheist_permutation_plot, "~/Documents/final_project_data_cleanup/shiny/religion/agnostic_or_atheist_permutation.rds")
             
```




