---
title: "Urban"
author: "Diego Arias"
date: "12/2/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(tidyverse)
library(googlesheets4)
library(janitor)
library(stats)
library(fs)
library(readxl)
library(infer)
library(pracma)
library(tidyverse)
library(googlesheets4)
library(janitor)
library(stats)
library(fs)
library(readxl)
library(infer)
library(pracma)
library(reshape2)
library(moderndive)
library(gt)
library(ggplot2)
```

```{r}
m <- read_csv("m.csv")
```

```{r urban distribution}
data_plot_urban <- ggplot(m, aes(x = urban_r, fill = urban_r)) +
  geom_bar(aes(y = (..count..)/sum(..count..))) +
  labs(title="Distribution of Data Points", x="Different Values", y= "Percentage")  +
  scale_y_continuous(labels = scales::percent)+
  theme(legend.position = "none")+
  theme(
  plot.background = element_rect(fill = "white"),
  panel.background = element_rect(fill = "white"),
  axis.line.x = element_line(color = "grey"))+
  theme(legend.title = element_blank())

data_plot_urban

write_rds(data_plot_urban, "~/Documents/final_project_data_cleanup/shiny/urban/barplot_urban.rds")
```

```{r urban violin}
urban_violin <- m %>%
  ggplot(aes(x=urban_r, y = n_same_urban, color = urban_r)) +
  geom_violin() +
  stat_summary(fun.y = mean, geom = "point") +
  geom_jitter(shape = 16, color = "black", size = .5, height = 0.1, width = 0.2) + 
  labs(title = "Distribution of Friends' Geographic Location per Respondents' Geographic Location", y = "Number of Friends with Same Geographic Origins", x = "Type of Geographic Origin of Respondent") +
  theme(legend.position = "none")+
  theme(
  plot.background = element_rect(fill = "white"),
  panel.background = element_rect(fill = "white"),
  axis.line.x = element_line(color = "grey"))+
  theme(legend.title = element_blank())

urban_violin


write_rds(urban_violin, "~/Documents/final_project_data_cleanup/shiny/urban/violin_urban.rds")
```


```{r urban for loop}
m_random_urban<-
    
  tibble(replicate = 1:10000) %>%
  
  mutate(urban_r = sample(c("Urban","Rural"), size=10000, replace = TRUE, prob=c(0.9,0.1)))%>%
  
  mutate(urban_p1 = sample(c("Urban","Rural"), size=10000, replace = TRUE, prob=c(0.9,0.1)))%>%
  
  mutate(urban_p2 = sample(c("Urban","Rural"), size=10000, replace = TRUE, prob=c(0.9,0.1)))%>%
  
  mutate(urban_p3 = sample(c("Urban","Rural"), size=10000, replace = TRUE, prob=c(0.9,0.1)))%>%
  
  mutate(urban_p4 = sample(c("Urban","Rural"), size=10000, replace = TRUE, prob=c(0.9,0.1)))%>%
  
  mutate(n_same_urban = NA)

# We repeat the same for loop as we did in the beginning with our collected data, but with the sample we generated with the for loop above:

for (i in 1:10000) {

respondent_urban<-m_random_urban$urban_r[i]

count=0

if(respondent_urban==m_random_urban$urban_p1[i])
{count<-count+1}else{
count<-count}

if(respondent_urban==m_random_urban$urban_p2[i])
{count<-count+1}else{
count<-count}

if(respondent_urban==m_random_urban$urban_p3[i])
{count<-count+1}else{
count<-count}

if(respondent_urban==m_random_urban$urban_p4[i])
{count<-count+1}else{
count<-count}

m_random_urban$n_same_urban[i]<-count}
```

```{r rural permutation}
rural_replications <- m_random_urban %>%
   filter(urban_r=="Rural")%>%
  select(n_same_urban)%>%
  rep_sample_n(size = 13, replace = TRUE, reps = 10000) %>% 
  group_by(replicate) %>% 
  summarize(mean_same_urban = mean(n_same_urban))

mean_observed_rural <- as.numeric(m%>%
  filter(urban_r=="Rural")%>%
  summarize(mean=mean(n_same_urban)))

rural_permutation_plot<- rural_replications %>%
  ggplot(aes(x=mean_same_urban))+
  geom_density(fill = "seagreen1")+
  geom_vline(xintercept=mean_observed_rural, color = "blue") + 
  labs(title = "Distribution of Mean Number of Friends with Rural Origins with a Respondent with Rural Origins", subtitle = "The distribution of the number of friends with the same geographical origins as the respondent", x = "Mean Number of Friend with Same Rural Origin per Rural Respondent per Replication", y = "Density")+
  theme(
  plot.background = element_rect(fill = "white"),
  panel.background = element_rect(fill = "white"),
  axis.line.x = element_line(color = "grey"))+
  theme(legend.title = element_blank())

rural_permutation_plot

write_rds(rural_permutation_plot, "~/Documents/final_project_data_cleanup/shiny/urban/rural_permutation.rds")
```


```{r urban permutation}
urban_replications <- m_random_urban %>%
   filter(urban_r=="Urban")%>%
  select(n_same_urban)%>%
  rep_sample_n(size = 54, replace = TRUE, reps = 10000) %>% 
  group_by(replicate) %>% 
  summarize(mean_same_urban = mean(n_same_urban))

urban_replications


  
mean_observed_urban <- as.numeric(m%>%
  filter(urban_r=="Urban")%>%
    drop_na()%>%
  summarize(mean=mean(n_same_urban)))
mean_observed_urban

urban_permutation_plot<- urban_replications %>%
  ggplot(aes(x=mean_same_urban))+
  geom_density(fill = "seagreen1")+
  geom_vline(xintercept= mean_observed_urban, color = "blue") + 
  labs(title = "Distribution of Mean Number of Friends with Urban Origins with a Respondent with Urban Origins", subtitle = "Our observed value, shown in blue, is bigger than we would expect under random friend assignment", x = "Mean Number of Friend with Same Urban Origin per Urban Respondent per Replication", y = "Density")+
  theme(
  plot.background = element_rect(fill = "white"),
  panel.background = element_rect(fill = "white"),
  axis.line.x = element_line(color = "grey"))+
  theme(legend.title = element_blank())

urban_permutation_plot

write_rds(urban_permutation_plot, "~/Documents/final_project_data_cleanup/shiny/urban/urban_permutation.rds")
```
